name: etc_math
channels:
  - conda-forge
  - bokeh
dependencies:
  - python=3.5
  - jupyter
  - pandas
  - numpy
  - scipy
  - ffmpeg
  - html5lib
  - ipywidgets
  - matplotlib
  - bokeh
  - nodejs
  - bqplot
  - tqdm
  - pyproj
  
