name: etc_math
channels:
  - conda-forge
  - bokeh
dependencies:
  - python
  - ipython
  - jupyter
  - pandas
  - pillow
  - numpy
  - scipy
  - ffmpeg
  - html5lib
  - BeautifulSoup4
  - lxml
  - ipywidgets
  - matplotlib
  - bokeh
  - nodejs
  - bqplot
  - tqdm
  - pyproj
  - icu
  - xlrd

